apiVersion: v1
kind: Service
metadata:
  name: dhanush-app-service
  namespace: dhanush-dev
spec:
  type: NodePort
  selector:
    app: dhanush-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
